## Data Information

Data have 5 columns and more than 100 million rows. There are about 1 million users whoes user behaviors including click, purchase, adding item to shopping cart and item favoring during November 25 to December 03, 2017. Each line represents a specific user-item interaction, which consists of user ID, item ID, item's category ID, behavior type and timestamp, separated by commas.

In [1]:
# Modules imported
import pandas as pd
import numpy as np
import matplotlib as plt

In [2]:
data = pd.read_csv('/Users/paxton615/Downloads/UserBehavior.csv')

In [3]:
data.shape

(3835330, 5)

In [4]:
data.isnull().sum()

1             0
2268318       0
2520377       0
pv            0
1511544070    0
dtype: int64

In [ ]:
data.nunique() # take 2-3 minutes to complete, be cautious to run this line

In [ ]:
data.head()

In [5]:
# col names = ['user_id', 'item_id','category_id','status',"timestamp"]
# pv: page view, buy: buy, cart: cart:, fav:favorite
data.columns = ['user_id', 'item_id','category_id','status',"timestamp"]

Trying some concert code here：

fun = data.head()
fun

str(pd.Timestamp(fun['timestamp'][0], unit='s'))[:10] 

convert str to timestamp
str(pd.Timestamp('2017-11-11').year)+'-'+str(pd.Timestamp('2017-11-11').month)

pd.Timestamp(fun['timestamp'][0], unit='s').hour

pd.Timestamp(fun['timestamp'][0], unit='s').month

It worked!

In [6]:
# select 3 million for analysis, calling them 'users'
users = data.iloc[5000000:8000000,:]

In [7]:
users.shape

(3000000, 5)

In [8]:
users.reset_index(drop=True, inplace=True)

In [9]:
users.head()

user_id  item_id  category_id status   timestamp
0   309818  4710383      1792277     pv  1511959603
1   309818  1421743      4069500     pv  1511959759
2   309818   800137      1216617     pv  1511959828
3   309818  2493122      1216617     pv  1511959953
4   309818  1461532      3102419     pv  1511998449

In [ ]:
users.nunique()

In [ ]:
# How much does ths sample, users, represent the population.
total_nuni = ['1 987994','2268318 4162024','2520377 9439','pv 4','1511544070 815859']

pop_unq = [int(i.split(' ')[1]) for i in total_nuni]
pop_unq

sample_unq = [i for i in users.nunique()]
sample_unq

perctage = []
for i,j in zip(sample_unq,pop_unq):
    perctage.append('{:2%}'.format(i/j))

# the subset, users, contains 3% of total users,
# 19% of total items, 73% of categories
perctage

In [10]:
users['hour']=[pd.Timestamp(i, unit='s',tz='Asia/Shanghai').hour for i in users.timestamp]

users['year']=[pd.Timestamp(i, unit='s',tz='Asia/Shanghai').year for i in users.timestamp]

users['day']=[pd.Timestamp(i, unit='s',tz='Asia/Shanghai').day for i in users.timestamp]

users['month']=[pd.Timestamp(i, unit='s',tz='Asia/Shanghai').month for i in users.timestamp]
# 0 is Monday，6 is Sunday
users['dayofweek']=[pd.Timestamp(i, unit='s',tz='Asia/Shanghai').dayofweek for i in users.timestamp]

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = 

In [11]:
users.year.unique() # data were generated during 2017-11-25 to 2017-12-3
# 2020,1919,2021 need to be found and cleaned later!

array([2017, 2020, 1919, 2021])

In [12]:
users[(users['year']==1919)| (users['year']==2021)|(users['year']==2020)].count()

user_id        28
item_id        28
category_id    28
status         28
timestamp      28
hour           28
year           28
day            28
month          28
dtype: int64

In [13]:
users = users[users['year']==2017] # only choose 2017 data

In [14]:
np.sort(users.hour.unique()) # hours seem normal

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [15]:
users.day.unique() 
# keep the days within 11.25-12.3

array([29, 30,  1,  2,  3, 27, 28, 25, 26, 24, 20, 23, 22, 17, 21, 14,  4,
        5, 16, 18, 19, 11, 12, 13, 15, 10])

In [16]:
users = users[users['day'].isin([25,26,27,28,29,30,1,2,3])] 

In [17]:
users.month.unique()
# data happened during 2017.11-2017.12, some months need to be cleaned

array([11, 12,  8, 10,  9])

In [18]:
users[(users['month']==10)| (users['month']==4)|(users['month']==9)|(users['month']==5)|(users['month']==8)].count()


user_id        24
item_id        24
category_id    24
status         24
timestamp      24
hour           24
year           24
day            24
month          24
dtype: int64

In [19]:
users = users[users['month'].isin([11,12])]

In [20]:
users.shape

(2998310, 9)

In [ ]:
users.head() 

In [ ]:
users.to_csv(r'/Users/paxton615/Github_Personal/Alibaba_UserBehavior_Analysis/drafts/users_3m.csv')

In [21]:
# dropduplicstes: same user,same day, same hour, viewed the same item 
users = users.drop_duplicates(subset=['user_id','item_id','status','hour','day'])


In [22]:
users.shape

(2748966, 9)

In [27]:
users.head()

user_id  item_id  category_id status   timestamp  hour  year  day  month  \
0   309818  4710383      1792277     pv  1511959603    20  2017   29     11   
1   309818  1421743      4069500     pv  1511959759    20  2017   29     11   
2   309818   800137      1216617     pv  1511959828    20  2017   29     11   
3   309818  2493122      1216617     pv  1511959953    20  2017   29     11   
4   309818  1461532      3102419     pv  1511998449     7  2017   30     11   

        date  dayofweek  
0 2017-11-29          2  
1 2017-11-29          2  
2 2017-11-29          2  
3 2017-11-29          2  
4 2017-11-30          3

In [25]:
# Form user['date'] by using year, month, day
date = []
for i,j,k in zip(users['year'], users['month'], users['day']):
    date.append(str(i)+"-"+str(j)+"-"+str(k))

users['date']=pd.to_datetime(date)

users.head()

user_id  item_id  category_id status   timestamp  hour  year  day  month  \
0   309818  4710383      1792277     pv  1511959603    20  2017   29     11   
1   309818  1421743      4069500     pv  1511959759    20  2017   29     11   
2   309818   800137      1216617     pv  1511959828    20  2017   29     11   
3   309818  2493122      1216617     pv  1511959953    20  2017   29     11   
4   309818  1461532      3102419     pv  1511998449     7  2017   30     11   

        date  
0 2017-11-29  
1 2017-11-29  
2 2017-11-29  
3 2017-11-29  
4 2017-11-30

In [28]:
# tidy cols and reset_index
users = users[['user_id', 'item_id' , 'category_id', 'status', 'date','dayofweek' ,'hour']]
users.reset_index(drop=True, inplace=True)

In [29]:
users.dtypes
# Could convert hour to datetime as well, however, don't see the need yet
# pd.to_datetime(users['hour'], format='%H')

user_id                 int64
item_id                 int64
category_id             int64
status                 object
date           datetime64[ns]
dayofweek               int64
hour                    int64
dtype: object

In [30]:
users.head()

user_id  item_id  category_id status       date  dayofweek  hour
0   309818  4710383      1792277     pv 2017-11-29          2    20
1   309818  1421743      4069500     pv 2017-11-29          2    20
2   309818   800137      1216617     pv 2017-11-29          2    20
3   309818  2493122      1216617     pv 2017-11-29          2    20
4   309818  1461532      3102419     pv 2017-11-30          3     7

In [31]:
users.to_csv(r'/Users/paxton615/Github_Personal/Alibaba_UserBehavior_Analysis/drafts/users_2m.csv')

# Saved , 2.7m entries.

In [32]:
# Modules imported
import pandas as pd
import numpy as np
import matplotlib as plt

In [33]:
users = pd.read_csv('/Users/paxton615/Github_Personal/Alibaba_UserBehavior_Analysis/drafts/users_2m.csv')


In [34]:
users.head()

Unnamed: 0  user_id  item_id  category_id status        date  dayofweek  \
0           0   309818  4710383      1792277     pv  2017-11-29          2   
1           1   309818  1421743      4069500     pv  2017-11-29          2   
2           2   309818   800137      1216617     pv  2017-11-29          2   
3           3   309818  2493122      1216617     pv  2017-11-29          2   
4           4   309818  1461532      3102419     pv  2017-11-30          3   

   hour  
0    20  
1    20  
2    20  
3    20  
4     7

In [35]:
users.drop('Unnamed: 0', axis=1, inplace=True)

In [36]:
users.head()

user_id  item_id  category_id status        date  dayofweek  hour
0   309818  4710383      1792277     pv  2017-11-29          2    20
1   309818  1421743      4069500     pv  2017-11-29          2    20
2   309818   800137      1216617     pv  2017-11-29          2    20
3   309818  2493122      1216617     pv  2017-11-29          2    20
4   309818  1461532      3102419     pv  2017-11-30          3     7

# 用户使用行为的漏斗模型

分析用户使用行为的漏斗模型，AARRR模型分析用户行为，此处数据主要涉及用户刺激和购买转化环节。
通过用户从浏览到最终购买过程的流失情况，包括浏览，收藏，加入购物车和购买。在本例中，各项指标如下:

In [37]:
# 访问用户总数 （UV）:29233
users.nunique()

user_id         29233
item_id        805830
category_id      6910
status              4
date                9
dayofweek           7
hour               24
dtype: int64

In [38]:
# 页面总访问量 （PV）：2406344
users.groupby('status')['user_id'].count()

status
buy       58537
cart     167988
fav       86553
pv      2435888
Name: user_id, dtype: int64

平均每人每周访问量

In [39]:
# Average PV per week per person
avg_pv = users.groupby('status')['user_id'].count().pv / users.user_id.nunique()
'{:.4}'.format(avg_pv)

'83.33'

跳失率：只点击一次浏览的用户数量/总用户访问量

user_stat_cnts0 = pd.DataFrame(users.groupby(['user_id','status'])['status'].count())

user_stat_cnts0.head()

user_stat_cnts0.loc[42,'pv']

user_stat_cnts1=user_stat_cnts0.reset_index(level=0)

user_stat_cnts1.head()

In [40]:
# 每个用户的pv数量是多少？逻辑：相当于通过按user_id来groupby，统计大类（status）中某个小类（pv）的数量
# 很重要的groupby应用实例，filter之后再做groupby
# 很重要，很重要
user_pv = pd.DataFrame(users[users['status']=='pv'].groupby(users['user_id'])['status'].count())
user_pv.columns=['pv']
user_pv.head()

pv
user_id     
34        32
42        50
43       119
310       69
311       34

In [41]:
# 只有一次浏览记录的用户有多少？
# 可见，非常少，可以忽略不计。
len(user_pv[user_pv['pv'] == 1])

23

In [42]:
# 所有user的总浏览量
users[users['status']=='pv']['user_id'].count()

2435888

In [43]:
# 跳失率
Bounce_rate = len(user_pv[user_pv['pv'] == 1]) / users[users['status']=='pv']['user_id'].count()

'{:.6%}'.format(Bounce_rate)


'0.000944%'

漏斗模型：
喜欢和放入购物车都属于决策环节，二者合一。
百分之多少的人从pv进入了cart和fav环节
又有百分之多少的人从cart和fav环节进入了最后的buy

In [44]:
users_status = users.groupby('status').user_id.count()
users_status

status
buy       58537
cart     167988
fav       86553
pv      2435888
Name: user_id, dtype: int64

In [65]:
# 约10.46%的用户从浏览环节进入决策环节
pv_to_cartnfav = (users_status[1]+users_status[2])/users_status[3]

'{:.2%}'.format(pv_to_cartnfav)

'10.45%'

In [66]:
# 约23.06%的用户从决策环节进入了购买环节，环比之前大幅提升
cartnfav_to_buy = users_status[0]/(users_status[1]+users_status[2])
'{:.3%}'.format(cartnfav_to_buy)

'22.997%'

# 不同时间尺度下，用户行为模式分析

1.分析一周内的用户使用情况

In [47]:
users.date.unique()

array(['2017-11-29', '2017-11-30', '2017-12-01', '2017-12-02',
       '2017-12-03', '2017-11-27', '2017-11-28', '2017-11-25',
       '2017-11-26'], dtype=object)

In [48]:
# ub is user behavior
ub_daily_old=pd.DataFrame(users.groupby(['date','status'], as_index=False).user_id.count())
ub_daily_old.head()


date status  user_id
0  2017-11-25    buy     5868
1  2017-11-25   cart    17040
2  2017-11-25    fav     9163
3  2017-11-25     pv   258856
4  2017-11-26    buy     5995

In [49]:
# .pivot() 以...为中心旋转 很重要很重要很重要
ub_daily = ub_daily_old.pivot(index='date',columns='status')
ub_daily

user_id                      
status         buy   cart    fav      pv
date                                    
2017-11-25    5868  17040   9163  258856
2017-11-26    5995  18057   9245  260688
2017-11-27    6566  16564   8817  246517
2017-11-28    6055  16468   8639  242771
2017-11-29    6299  16771   8885  247401
2017-11-30    6458  17192   9177  251903
2017-12-01    6137  18759   9088  264524
2017-12-02    7707  23909  12058  334480
2017-12-03    7452  23228  11481  328748

In [50]:
# 好像可以对multi_colums的col name直接做修改
ub_daily.columns = ['buy', 'cart', 'fav', 'pv']



In [51]:
# 改名后调整cols的顺序
ub_daily = ub_daily[['pv','fav','cart','buy']]
ub_daily

pv    fav   cart   buy
date                                  
2017-11-25  258856   9163  17040  5868
2017-11-26  260688   9245  18057  5995
2017-11-27  246517   8817  16564  6566
2017-11-28  242771   8639  16468  6055
2017-11-29  247401   8885  16771  6299
2017-11-30  251903   9177  17192  6458
2017-12-01  264524   9088  18759  6137
2017-12-02  334480  12058  23909  7707
2017-12-03  328748  11481  23228  7452

小结论：
11-29为周三，11-25为周六，12-03为周日
周一到周五数据趋于稳定，周末数据有明显增加，运营活动可向周末时间倾斜

2. 分析用户一天内的使用情况

In [ ]:
users.head()

In [ ]:
nov_28 = users[users['date']=='2017-11-29'][['user_id','status','hour']]

In [ ]:
nov_28.head()

In [ ]:
temp = nov_28.groupby(['hour','status'],as_index=False).count()

In [ ]:
temp.head()

In [ ]:
nov_28 = temp.pivot(index='hour',columns='status')

In [ ]:
nov_28.head()

In [ ]:
nov_28.columns=['buy', 'cart', 'fav', 'pv']

In [ ]:
nov_28 = nov_28[['pv','fav','cart','buy']]
nov_28.head()

# 此处发现一个大问题，11-28号，简书的案例中显示21，22点是用户最活跃的时间，而我的timestamp读取出的时间是13，14点！！！需返回后重新检查... ... (已返回，且问题已通过加入上海时区而解决)

In [ ]:
# 设计一个function，将制定数据自动转换成某日的四种状态浏览记录
def daily_status(df,str_colname1,str_colname2,str_colname3):
    temp = df.groupby([str_colname3,str_colname2],as_index=False).count()
    daily_num = temp.pivot(index=str_colname3,columns=str_colname2)
    daily_num.columns=['buy', 'cart', 'fav', 'pv']
    daily_num = daily_num[['pv','fav','cart','buy']]
    return (daily_num)

In [ ]:
nov_29=users[users['date']=='2017-11-29'][['user_id','status','hour']]

In [ ]:
daily_status(nov_29,'user_id','status','hour').sort_values('pv',ascending=False).head(7)

In [ ]:
# "2017-12-02" correct ; "2017-12-2" incorrect
dec_2=users[users['date']=='2017-12-02'][['user_id','status','hour']]

In [ ]:
daily_status(dec_2,'user_id','status','hour').sort_values('pv',ascending=False).head(7)

小结论：从每天的数据情况来看，20-23是绝对使用高峰期，应该在此时间段内增加互动营销，以希望更大收益

# 不同商品种类的用户行为

1. 统计浏览次数，购买次数，收藏次数，和加入购物车次数最多的商品

In [ ]:
users.head()

In [ ]:
# top item been seen
users[users['status']=='pv'][['item_id','user_id']].groupby('item_id').count().sort_values('user_id',ascending=False).head()

In [ ]:
# top items been bought
users[users['status']=='buy'][['item_id','user_id']].groupby('item_id').count().sort_values('user_id',ascending=False).head(20)

In [ ]:
# top items in fav
users[users['status']=='fav'][['item_id','user_id']].groupby('item_id').count().sort_values('user_id',ascending=False).head(20)

In [ ]:
# top items in cart
users[users['status']=='cart'][['item_id','user_id']].groupby('item_id').count().sort_values('user_id',ascending=False).head(20)

In [ ]:
# 以上四幅图需要一个能有效结合在一起的方式，没有比较，几幅图的意义不大。
# 最好是图形的。

2. 统计所有商品的购买次数

In [ ]:
users.head()

In [ ]:
users[users['status']=='buy'][['item_id','user_id']].head()

In [ ]:
item_buytimes = users[users['status']=='buy'][['item_id','user_id']].groupby('item_id', as_index=False).count().sort_values('user_id',ascending=False)

In [ ]:
item_buytimes.head()

In [ ]:
# There are 38449 kinds of iterms that only been bought once
# only one item was bought 34 times
item_buytimes.groupby('user_id').count()

In [ ]:
item_buytimes_stas = pd.DataFrame(item_buytimes.groupby('user_id').count())

In [ ]:
'{:.2%}'.format(item_buytimes_stas.item_id[1]/sum(item_buytimes_stas.item_id))

84.34%这个数据说明，大部分的销售来源于长尾商品的累积效应。而非爆款商品的带动。

# 基于RFM理论找出有价值的用户

In [ ]:
users.head()

In [ ]:
len(users[users['status']=='buy'].groupby('user_id',as_index=False)['date'].agg(['max']))

In [ ]:
# the most recent shopping record of each user
recent_buy = users[users['status']=='buy'].groupby('user_id',as_index=False)['date'].agg(['max'])

In [ ]:
recent_buy.head()

In [ ]:
recent_buy.columns=['latest_shopping']
recent_buy.reset_index(inplace=True)

In [ ]:
recent_buy.head()

In [ ]:
np.sort(recent_buy.latest_shopping.unique())

In [ ]:
recent_buy['latest_shopping'][1]>'2017-11-02'

In [ ]:
recent_buy['R'] = [0 if '2017-11-25'<= i <='2017-11-27' 
                   else 1 if '2017-11-28' <= i <= '2017-11-30' 
                   else 2 for i in recent_buy.latest_shopping]




In [ ]:
recent_buy.head()

In [ ]:
shopping_freq = users[users['status']=='buy'].groupby('user_id', as_index=False).item_id.count()

In [ ]:
shopping_freq.head()

In [ ]:
shopping_freq[shopping_freq['user_id']==339189]

In [ ]:
shopping_freq.item_id.unique()

In [ ]:
shopping_freq['F'] = [ 5 if i >= 50 
                     else 4 if 49 >= i >= 40
                     else 3 if 39 >= i >= 30
                     else 2 if 29 >= i >= 20
                     else 1 for i in shopping_freq.item_id]

In [ ]:
shopping_freq.head()

In [ ]:
shopping_freq[shopping_freq['user_id']==337305]

In [ ]:
rfm = pd.merge(recent_buy, shopping_freq, on='user_id')[['user_id','latest_shopping','R','F']]

In [ ]:
rfm['R+F'] = rfm['R']+rfm['F']

In [ ]:
rfm.head()

In [ ]:
rfm[rfm['user_id']==337305]

In [ ]:
rfm['R+F'].value_counts(normalize=True)

In [ ]:
1.5/11.4

In [ ]:
7.2/22